// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2X83LdXkFc9dxWiz74Jg__XYkoBqu014',
    appId: '1:400628582389:web:b7bc8c9a51b184d0a202bc',
    messagingSenderId: '400628582389',
    projectId: 'traningcourse-bb860',
    authDomain: 'traningcourse-bb860.firebaseapp.com',
    storageBucket: 'traningcourse-bb860.appspot.com',
    measurementId: 'G-XGW8WB20YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwh2JkkJxvghB5Y9EgEP7QHHzKhb6Zok',
    appId: '1:400628582389:android:d33753a967362189a202bc',
    messagingSenderId: '400628582389',
    projectId: 'traningcourse-bb860',
    storageBucket: 'traningcourse-bb860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9P9exp7BKGcl_9jcUPyfr-OV7s-tlc8',
    appId: '1:400628582389:ios:9b2a5da9c6aec4f1a202bc',
    messagingSenderId: '400628582389',
    projectId: 'traningcourse-bb860',
    storageBucket: 'traningcourse-bb860.appspot.com',
    iosBundleId: 'com.example.newtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj9P9exp7BKGcl_9jcUPyfr-OV7s-tlc8',
    appId: '1:400628582389:ios:9b2a5da9c6aec4f1a202bc',
    messagingSenderId: '400628582389',
    projectId: 'traningcourse-bb860',
    storageBucket: 'traningcourse-bb860.appspot.com',
    iosBundleId: 'com.example.newtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2X83LdXkFc9dxWiz74Jg__XYkoBqu014',
    appId: '1:400628582389:web:0e1b1f1ba7bb2435a202bc',
    messagingSenderId: '400628582389',
    projectId: 'traningcourse-bb860',
    authDomain: 'traningcourse-bb860.firebaseapp.com',
    storageBucket: 'traningcourse-bb860.appspot.com',
    measurementId: 'G-1TN2PKD816',
  );

}